<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>
<script src="https://www.google.com/recaptcha/api.js" type="text/javascript" xml="space"></script>

<div class="row custom-forgot-page ml-0 mr-0">
    <div class="col-12 col-lg-6 pl-lg-0 pr-lg-0 forgot-left">
        <div class="forgot-img-wall" >
                <?php echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('customer_forgot_image')
                ->toHtml(); ?>
            </div>
    </div>
    <div class="col-12 col-lg-6 pl-lg-0 pr-lg-0 forgot-right">
        <!-- <h2 class="custom-forgot-title">
            <?php //echo __("Forgot Password") ?>
        </h2> -->
        <div class="custom-forgot-title">
            <strong id="block-customer-forgot-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Forgot Password')) ?></strong>
        </div>
        <form class="form password forgot" action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
            method="post" id="form-validate" data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                <div class="field note">
                    <?= $block->escapeHtml(__('Please enter your email address below to receive a password reset link.')) ?>
                </div>
                <div class="field email required">
                    <div>
                        <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                    </div>
                    <div class="control">
                        <input placeholder="Type email here" type="email" name="email" alt="email" id="email_address"
                            class="input-text" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>"
                            data-mage-init='{"mage/trim-input":{}}'
                            data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
                <div class="forgot-recaptcha-row">
                    <div class="field captcha required form-group">
                        <div class="g-recaptcha required" id="recaptcha"
                            data-sitekey="6LfCzoEaAAAAAPDBOLv3-YqtES-efe8EtmLS9Wxb">
                        </div>
                        <div style="display:none" id="error-msg">
                            <span><?php echo __('This is a required field.') ?></span>
                        </div>
                    </div>
                </div>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="submit"
                            class="action submit primary"><span><?= $block->escapeHtml(__('Reset My Password')) ?></span></button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "form-validate"
            }
        }
    }
</script>