<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Customer\Block\Form\Login $block 
 * @var  \Mancini\CustomerSignIn\Helper\Data $_helper
 */
?>
<?php
$_helper            =   $this->helper('Mancini\CustomerSignIn\Helper\Data');

$loginEmail         =   $_helper->getCookieloginName();
$loginPassword      =   $_helper->getCookieloginPwd();

?>
<script src="https://www.google.com/recaptcha/api.js" type="text/javascript" xml="space"></script>
<div class="custom-login-page row ml-0 mr-0">
    <div class="col-12 col-lg-6 pl-lg-0 pr-lg-0 login-left">
        <div class="login-img-wall" >
                <?php echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('customer_login_image')
                ->toHtml(); ?>
        </div>  
   </div>
    <div class="col-12 col-lg-6 pl-lg-0 pr-lg-0 login-right">
        <div class="block block-customer-login">
            <div class="block-title custom-login-title">
                <strong id="block-customer-login-heading" role="heading"
                    aria-level="2"><?= $block->escapeHtml(__('Log in as existing customer')) ?></strong>
            </div>
            <div class="block-content" aria-labelledby="block-customer-login-heading">
                <form class="form form-login" action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
                    method="post" id="login-form" data-mage-init='{"validation":{}}'>
                    <?= $block->getBlockHtml('formkey') ?>
                    <fieldset class="fieldset login"
                        data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
                        <!-- <div class="field note">
                            <?//= $block->escapeHtml(__('If you have an account, sign in with your email addressssss.')) ?>
                        </div> -->
                        <div class="field email required">
                            <div>
                                <label class="label" for="loginEmail"><span><?= $block->escapeHtml(__('Email')) ?></span>
                                </label>
                            </div>
                            <div class="control">
                                <input id="loginEmail" name="login[username]"
                                    value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>"
                                    <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off" <?php endif; ?>
                                    id="email" type="email" placeholder="Type email here" class="input-text"
                                    title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                                    data-mage-init='{"mage/trim-input":{}}'
                                    data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>
                        <div class="field password required">
                            <div>
                                <label for="loginPass" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span>
                                </label>
                            </div>
                            <div class="control">
                                <input id="loginPass" name="login[password]" type="password"
                                    <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off" <?php endif; ?>
                                    class="input-text" placeholder="Type password here"
                                    title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                                    data-validate="{required:true}">
                                <img role="checkbox" aria-checked="false" tabindex="0" class="show-password-eye" id="eye-disable-enable" onclick="showPassword()" onkeypress="showPassword()"
                                    src='<?php echo $block->getViewFileUrl('images/eye.svg'); ?>' alt=" eye">
                            </div>
                        </div>
                        <div class="links">

                            <!-- remember me checkbox -->
                            <div class="remember_me field rememberme">
                                <label role="checkbox" aria-checked="false" tabindex="0" class="check-container">
                                    <input type="checkbox" name="login[rememberme]" tabindex="3" value="remember-me"
                                    id="rememberme"><label for="rememberme" class="input-checkbox"
                                    <?php if ($_helper->getCookieloginChk()) { ?>checked="checked" <?php } ?>>
                                    <span><?php /* @escapeNotVerified */ echo __('Remember Me') ?></span></label>
                                    <span class="cus-check"></span>
                                </label>
                            </div>
                            <div class="secondary"><a class="action remind"
                                    href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span></a>
                            </div>
                        </div>
                        <?= $block->getChildHtml('form_additional_info') ?>
                        <div class="actions-toolbar">
                            <div class="primary"><button type="submit" class="action login primary" name="send"
                                    id="send2"><span><?= $block->escapeHtml(__('Log In')) ?></span></button></div>
                        </div>
                        <div class="create-account-link">
                            <span><?php echo __("New Customer? ") ?></span><u><a
                                href="<?php echo $block->getUrl('customer/account/create'); ?>"
                                class="action create"><span><?php echo __('Create a new Account') ?></span></a></u>

                        </div>
                    </fieldset>
                </form>
            </div>
            <script type="text/x-magento-init">
                {
                    "*": {
                        "Magento_Customer/js/block-submit-on-send": {
                        "formId": "login-form"
                        }
                    }
                }
            </script>
            <script type="text/javascript">
            {
                function showPassword() {
                    var x = document.getElementById("loginPass");
                    var y = document.getElementById("eye-disable-enable");
                    if (x.type === "password") {
                        x.type = "text";
                    } else {
                        x.type = "password";
                    }
                    if(x.type === "password"){
                        y.src='<?php echo $block->getViewFileUrl('images/eye.svg'); ?>'
                    }
                    else{
                        y.src='<?php echo $block->getViewFileUrl('images/eye_disable.svg'); ?>'
                        console.log("image change");
                    }
                }
            }
            </script>
            <!-- js for setting credentials to the input fields -->
            <script type="text/javascript">
            function autoFill() {
                document.getElementById('loginEmail').value = "<?php echo $loginEmail ?>";
                document.getElementById('loginPass').value = "<?php echo $loginPassword ?>";
            }
            window.onload = autoFill();


            </script>
            <script type="text/x-magento-init">
            {
		        "#loginPass": { 
			        "Mancini_CustomerSignIn/js/login_error": {
			    } 
		    } 
	    }
            </script>


        </div>
    </div>
</div>