<?php
/** @var \Mirasvit\Gdpr\Block\Customer\Account\Anonymize $block */
?>
<br><br>
<div class="block">
    <div class="block-title">
        <strong><?= __('Download personal data') ?></strong>
    </div>

    <div class="block-content">
        <form method="post" action="<?= $block->getUrl('gdpr/customer/download') ?>" data-mage-init='{"validation":{}}'>
            <input name="form_key" type="hidden" value="<?= $block->getFormKey() ?>"/>

            <fieldset class="fieldset" hidden="hidden" id="download-form">
                <div class="field required">
                    <label class="label" for="current-password">
                        <span><?= __('Current Password') ?></span>
                    </label>
                    <div class="control">
                        <input type="password" class="input-text" name="password" autocomplete="off" aria-required="true" data-validate="{required:true}">
                    </div>
                </div>

                <div class="actions-toolbar">
                    <button type="submit" class="action primary">
                        <span><?= __('Download') ?></span>
                    </button>
                </div>
            </fieldset>
        </form>

        <div id="download-intro">
            <p><?= __('You can download all your data that we have stored by clicking the button below:') ?></p>
            <div class="actions-toolbar">
                <button type="button" class="action" data-show="download-form" data-hide="download-intro">
                    <span><?= __('Process') ?></span>
                </button>
            </div>
        </div>
    </div>
</div>

<script type="text/x-magento-init"><?= \Mirasvit\Core\Service\SerializeService::encode(['*' => ['Mirasvit_Gdpr/js/customer/account/requestForm' => []]]) ?></script>