<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_Xsearch
 */
?>
<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>

<div class="amsearch-additional-content">
    <div class="amsearch-leftside-sidebar" data-amsearch-js="leftside-sidebar">
        <?= $block->getChildHtml('sidebar') ?>
    </div>
    <?= $block->getChildHtml('main_panel') ?>
</div>
