<style>
	.tbb{
    	height: 37.6rem;
    	padding: 4rem;
		background-image:url(<?php echo $block->getViewFileUrl('images/try-before-you-buy.png'); ?>);
	}
	.tbb-text{
		width: 22.5rem;
    	height: 29.6rem;
    	padding-top: 5rem;
    	padding-bottom: 5rem;
    	padding-right: 3rem;
    	padding-left: 3rem;
    	background-color: rgba(255,255,255,0.9);
	}
	.tbb-text-head{
		    font-size: 30px !important;
	}
	.tbb-loc{
		    background-color: rgba(255,255,255,0.9);
    	width: 48rem;
    	height: 29.6rem;
    	padding: 4rem;
    	padding-top: 2.5rem;
	}
</style>

<div class="tbb-container">
<div class="row tbb">
	<div class="col-3">
		<div class="tbb-text">
			<h1 class="tbb-text-head" >TRY BEFORE YOU BUY !</h1>
			<br>
			<p>You Can try your selected products at your nearest store before you buy</p>
		</div>
	</div>
	<div class="col-4">
	</div>
	<div class="col-5">
		<div class="tbb-loc">
			<p>Find Your Nearby store Location to try</p>			
		</div>
	</div>
</div>
</div>