<div class="warranty">
    <hr>
    <div class="warranty-row">
        <div class=" warranty-col">
            <div class="img">
                <img class="warranty-img" src='<?php echo $block->getViewFileUrl('images/warranty.png'); ?>' alt="warranty">
            </div>
            <div class="text">
                10 Years' Warranty
            </div>
        </div>
        <div class=" warranty-col">
            <div class="img">
                <img class="warranty-img" src='<?php echo $block->getViewFileUrl('images/financing.png'); ?>' alt="financing">
            </div>
            <div class="text">
                Financing Available
            </div>
        </div>
        <div class=" warranty-col">
            <div class="img">
                <img class="warranty-img" src='<?php echo $block->getViewFileUrl('images/deliverydate.png'); ?>' alt="delivery">
            </div>
            <div class="text delivery-text">
                Delivery within 10 Days
            </div>
        </div>
    </div>
    <hr>
    <div class="warranty-row">
        <div class=" warranty-col">
            <div class="img">
                <img class="warranty-img" src='<?php echo $block->getViewFileUrl('images/warranty.png'); ?>' alt="warranty">
            </div>
            <div class="text">
                10 Years' Warranty
            </div>
        </div>
        <div class=" warranty-col">
            <div class="img">
                <img class="warranty-img" src='<?php echo $block->getViewFileUrl('images/financing.png'); ?>' alt="financing">
            </div>
            <div class="text">
                Financing Available
            </div>
        </div>
        <div class=" warranty-col">
            <div class="img">
                <img class="warranty-img" src='<?php echo $block->getViewFileUrl('images/deliverydate.png'); ?>' alt="delivery">
            </div>
            <div class="text delivery-text">
                Delivery within 10 Days
            </div>
        </div>
    </div>
    <hr>
</div>