<?php
/** @var \Synchrony\DigitalBuy\ViewModel\Modal\Payment $viewModel */
$viewModel = $block->getData('viewModel');
$address = $viewModel->getAddress();
$promoAmounts = $viewModel->getPromoAmounts();
$defaultPromoCode = $viewModel->getDefaultPromoCode();
?>
<div id="checkout" class="checkout-container">
    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img src="<?php echo $block->escapeHtmlAttr($block->getViewFileUrl('images/loader-1.gif')) ?>" alt="<?php echo $block->escapeHtmlAttr(__('Loading...')) ?>" style="position: absolute;">
        </div>
    </div>
    <div id="dbuymodel2"/>
    <form name="dbuyform2" id="dbuyform2">
        <input type="hidden" name="processInd" value="2"/>
        <input type="hidden" name="tokenId" value="<?php echo $block->escapeHtmlAttr($viewModel->getDigitalBuyTokenFromRegistry()) ?>"/>
        <input type="hidden" name="merchantID" value="<?php echo $block->escapeHtmlAttr($viewModel->getDigitalBuyMerchantId()) ?>"/>
        <input type="hidden" name="custFirstName" value="<?php echo $block->escapeHtmlAttr($address->getFirstname()) ?>"/>
        <input type="hidden" name="custLastName" value="<?php echo $block->escapeHtmlAttr($address->getLastname()); ?>"/>
        <input type="hidden" name="cardNumber" value=""/>
        <?php $street = $address->getStreet(); ?>
        <input type="hidden" name="custAddress1" value="<?php echo $block->escapeHtmlAttr($street[0]) ?>"/>
        <input type="hidden" name="custAddress2" value="<?php echo $block->escapeHtmlAttr(isset($street[1]) ? $street[1] : '') ?>"/>
        <input type="hidden" name="custCity" value="<?php echo $block->escapeHtmlAttr($address->getCity()) ?>"/>
        <input type="hidden" name="custState" value="<?php echo $block->escapeHtmlAttr($viewModel->getRegionCode($address->getRegionId())) ?>"/>
        <input type="hidden" name="custZipCode" value="<?php echo $block->escapeHtmlAttr($address->getPostcode()) ?>"/>
        <?php $i = 1; ?>
        <?php if(isset($promoAmounts)):?>
            <?php foreach ($promoAmounts as $promoCode => $promotionAmount): ?>
                <input type="hidden" name="transPromo<?php echo $i; ?>" value="<?php echo $block->escapeHtmlAttr($promoCode); ?>"/>
                <input type="hidden" name="transAmount<?php echo $i; ?>" value="<?php echo $block->escapeHtmlAttr($promotionAmount) ?>"/>
                <?php $i++; ?>
            <?php endforeach; ?>
        <?php endif; ?>
        <?php if (isset($promoAmounts) && count($promoAmounts) > 1): ?>
            <input type="hidden" name="defaultPromoCode" value="<?php echo $block->escapeHtmlAttr($defaultPromoCode) ?>"/>
        <?php endif; ?>
    </form>

    <form name="postbackform" id="postbackform" method="post" action="<?php echo $block->escapeHtmlAttr($block->getUrl('digitalbuy/revolving/modal_payment_complete')) ?>">
        <?php echo $block->getBlockHtml('formkey') ?>
        <input type="hidden" name="tokenId" value="<?php echo $block->escapeHtmlAttr($viewModel->getDigitalBuyTokenFromRegistry()); ?>"/>
        <input type="hidden" name="timestamp" value="<?php echo /* @noEscape */ $viewModel->getCurrentTimestamp(); ?>"/>
    </form>
    <script type="text/javascript">
        var digitalBuyModalManagerInitialized = false;
        var digitalBuyModalManagerInitCallback = function() {
            if (digitalBuyModalManagerInitialized) {
                return;
            }
            digitalBuyModalManagerInitialized = true;
            DigitalBuyModalManager.init({
                formId: "dbuyform2",
                postbackFormId: "postbackform"
            });
        };

        if (document.addEventListener) {
            document.addEventListener("DOMContentLoaded", digitalBuyModalManagerInitCallback, false);
            window.addEventListener("load", digitalBuyModalManagerInitCallback, false);
        } else if (document.attachEvent) {
            document.attachEvent("onreadystatechange", function () {
                if (document.readyState === "complete") {
                    digitalBuyModalManagerInitCallback();
                }
            });
            window.attachEvent("onload", digitalBuyModalManagerInitCallback);
        } else {
            digitalBuyModalManagerInitCallback();
        }
    </script>
</div>
