<?php  $_helper            =   $this->helper('Mancini\FooterSignin\Helper\Data'); ?>

<?php if($_helper ->isCustomerLoggedIn()): ?>
<?php //add the Myaccount link?>
<li class="list-number"><a class="menu-content" tabindex="0" href="/my-account">
        <?php echo __("My Account") ?></a></li>
<?php else: ?>
<?php //add the Signin link?>
<li class="list-number"><a class="menu-content" tabindex="0" href="/account/sign-in">Sign-In</a>
</li>
<li class="list-number"><a class="menu-content" tabindex="0" href="/account/sign-up">
        <?php echo __("Create Account") ?></a></li>
<?php endif;?>