<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<p class="toolbar-amount" id="toolbar-amount">
     <span class="toolbar-number"><?php  echo $block->getTotalNum()?></span>
     <span class="toolbar-number"><?php echo __('Results') ?></span>
</p>
