<?php

/**
 * Copyright Â© Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Magento\Wishlist\Block\Catalog\Product\ProductList\Item\AddTo\Wishlist $block */
?>

<?php if ($block->getWishlistHelper()->isAllow()) : ?>

    <?php
    //logger
    $writer = new \Zend\Log\Writer\Stream(BP . '/var/log/night_wishlist.log');
    $logger = new \Zend\Log\Logger();
    $logger->addWriter($writer);
    $logger->info('Line No. 17');
    ?>


    <?php
    //     //logger
    //     $writer = new \Zend\Log\Writer\Stream(BP . '/var/log/night_wishlist.log');
    //     $logger = new \Zend\Log\Logger();
    //     $logger->addWriter($writer);
    //     $logger->info($customerSession );


    $_loggedin = $block->getLayout()->createBlock('Magento\Customer\Block\Account\AuthorizationLink')->isLoggedIn();
    //logger
    $writer = new \Zend\Log\Writer\Stream(BP . '/var/log/night_wishlist.log');
    $logger = new \Zend\Log\Logger();
    $logger->addWriter($writer);
    $logger->info('Line No. 34');

    if ($_loggedin) {
        //logger
        // $writer = new \Zend\Log\Writer\Stream(BP . '/var/log/night_wishlist.log');
        // $logger = new \Zend\Log\Logger();
        // $logger->addWriter($writer);
        // $logger->info('Line No. 41');

    ?>

        <a href="javascript:void(0);" class="action custom-wishlist" id="custom-wishlist-<?php echo $block->getProduct()->getId(); ?>" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>" aria-label="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>" role="button" data-productid="<?php echo $block->getProduct()->getId(); ?>">
            <img class="whislist-icon product-id-<?php echo $block->getProduct()->getId(); ?>" src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/whislist-unfilled.svg'); ?>" alt="Add to wishlist" />
            <?php
            $_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface');
            $currentStore = $storeManager->getStore();
            $mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
            $wishimage = $mediaUrl . "wysiwyg/wishlist_color.png";
            ?>
            <img class="whislist-icon show-img-<?php echo $block->getProduct()->getId(); ?>" src="<?php /* @escapeNotVerified */ echo $wishimage; ?>" style="display:none;" alt="Added to wishlist" />
            <span><?= $block->escapeHtml(__('Added to Wish List')) ?></span>
        </a>



        <?php
        //logger
        $writer = new \Zend\Log\Writer\Stream(BP . '/var/log/night_wishlist.log');
        $logger = new \Zend\Log\Logger();
        $logger->addWriter($writer);
        $logger->info('Line No. 49');
        ?>



    <?php } else { ?>









        <a href="#" class="action towishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>" aria-label="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>" data-post='<?=/* @noEscape */ $block->getAddToWishlistParams($block->getProduct()) ?>' data-action="add-to-wishlist" role="button">

            <img class="whislist-icon product-id1-<?php echo $block->getProduct()->getId(); ?>" src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/whislist.png'); ?>" alt="Add to wishlist" />

            <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
        </a>

    <?php } ?>









    <!-- <script>
require(['jquery','Magento_Customer/js/customer-data'], function($,customerData){
    $( ".custom-wishlist" ).click(function() {
        var productId = $(this).attr('data-productid');
        jQuery.ajax({
            url: '<?php //echo $this->getUrl('customwishlist/index/wishlist') 
                    ?>',
            method: 'get',
            dataType: 'json',
            data: {
                productId: productId
            },
            success: function(data) {
                console.log(data.productid);
                var productId = data.productid;
                $(".product-id-"+productId).hide();
                $(".show-img-"+productId).show();
                //Do whatever you want to do
                var sections = ['wishlist'];
                customerData.invalidate(sections);
                customerData.reload(sections, true);
            }
        });
    });
});
</script> -->

<?php endif; ?>