<?php
/** @var \Synchrony\DigitalBuy\ViewModel\Modal\Revolving\Auth $viewModel */
$viewModel = $block->getData('viewModel');
$token = $viewModel->getDigitalBuyTokenFromRegistry();
$address = $viewModel->getAddress();
?>
<div id="checkout" class="checkout-container">
    <div id="checkout-loader" class="loading-mask">
        <div class="loader">
            <img src="<?php echo $block->escapeHtmlAttr($block->getViewFileUrl('images/loader-1.gif')) ?>"  alt="<?php echo $block->escapeHtmlAttr(__('Loading...')) ?>" style="position: absolute;">
        </div>
    </div>
    <div id="dbuymodel1"></div>
    <form name="dbuyform1" id="dbuyform1">
        <input type="hidden" name="processInd" value="1"/>
        <input type="hidden" name="tokenId" value="<?php echo $block->escapeHtmlAttr($token); ?>"/>
        <input type="hidden" name="merchantID" value="<?php echo $block->escapeHtmlAttr($viewModel->getDigitalBuyMerchantId()); ?>"/>
        <input type="hidden" name="clientTransId" value="<?php echo $block->escapeHtmlAttr($viewModel->getDigitalBuyClientTransId()); ?>" />
        <input type="hidden" name="custFirstName" value="<?php echo $block->escapeHtmlAttr($address->getFirstname()); ?>"/>
        <input type="hidden" name="custLastName" value="<?php echo $block->escapeHtmlAttr($address->getLastname()); ?>"/>
        <input type="hidden" name="custZipCode" value="<?php echo $block->escapeHtmlAttr($address->getPostcode()); ?>"/>
        <input type="hidden" name="cardNumber" value=""/>
    </form>

    <form name="postbackform" id="postbackform" method="post" action="<?php echo $block->escapeHtmlAttr($viewModel->getAuthCompleteUrl()) ?>">
        <?php echo $block->getBlockHtml('formkey') ?>
        <input type="hidden" name="tokenId" value="<?php echo $block->escapeHtmlAttr($token); ?>"/>
        <input type="hidden" name="timestamp" value="<?php echo /* @noEscape */ $viewModel->getCurrentTimestamp(); ?>"/>
    </form>

    <script type="text/javascript">
        var digitalBuyModalManagerInitialized = false;
        var digitalBuyModalManagerInitCallback = function() {
            if (digitalBuyModalManagerInitialized) {
                return;
            }
            digitalBuyModalManagerInitialized = true;
            DigitalBuyModalManager.init({
                formId: "dbuyform1",
                postbackFormId: "postbackform"
            });
        };

        if (document.addEventListener) {
            document.addEventListener("DOMContentLoaded", digitalBuyModalManagerInitCallback, false);
            window.addEventListener("load", digitalBuyModalManagerInitCallback, false);
        } else if (document.attachEvent) {
            document.attachEvent("onreadystatechange", function () {
                if (document.readyState === "complete") {
                    digitalBuyModalManagerInitCallback();
                }
            });
            window.attachEvent("onload", digitalBuyModalManagerInitCallback);
        } else {
            digitalBuyModalManagerInitCallback();
        }
    </script>
</div>
