<!-- <div id="floating-error" class="floating-error"><?php// echo "All Floating Errors"; ?></div> -->
<!-- <div class="alert alert-danger alert-dismissible fade show" role="alert">
    This is a danger alert with <a href="javascript:void(0)" class="alert-link">an example link</a>. Give it a click if
    you like.
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
</div> -->
<div class="alert">
    <span>
        <img src="<?php echo $block->getViewFileUrl('Mancini_FloatingError::images/up.png'); ?>" />
    </span>
    <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
    <span>Looks like error occurred oops we ran to the problem please Refresh the pages</span>
</div>