<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post next and prev post links
 *
 * @var $block \Magefan\Blog\Block\Post\View\NextPrev
 */
?>

<?php if ($block->displayLinks()) { ?>
<?php
    $prevPost = $block->getPrevPost();
    $nextPost = $block->getNextPost();
    ?>
<?php if ($prevPost || $nextPost) { ?>
<!-- <div class="post-nextprev-hld clearfix">
            <?php if ($prevPost) { ?>
                <?php $title = $prevPost->getTitle() ?>
                <a class="nextprev-link prev-link" href="javascript: history.go(-1)"
                   title="<?= $block->escapeHtml(__('Read %1', $title)) ?>">
                    <?= $block->escapeHtml(__('&lt; Back')) ?>
                </a>
            <?php } ?>
            <?php if ($nextPost) { ?>
                <?php $title = $block->escapeHtml($nextPost->getTitle()) ?>
                <a class="nextprev-link next-link" href="#" title="<?= $block->escapeHtml(__('Read %1', $title)) ?>">
                    <?= $block->escapeHtml(__('Go to Top &and;')) ?>
                </a>
            <?php } ?>
        </div>-->
<?php } ?>
<?php } ?>
<div class="post-nextprev-hld clearfix">
    <a class="nextprev-link prev-link" href="javascript: history.go(-1)" title="<?= $block->escapeHtml(__('Back')) ?>">
        <img src='<?php echo $this->getViewFileUrl('images/prev-arrow.svg'); ?>' alt="Previous">
        <?= $block->escapeHtml(__('Back')) ?>
    </a>
    <a class="nextprev-link next-link" href="#" title="<?= $block->escapeHtml(__('Go to Top')) ?>">
        <?= $block->escapeHtml(__('Go to Top ')) ?>
        <img src='<?php echo $this->getViewFileUrl('images/top-arrow.svg'); ?>' alt="Top">
    </a>
</div>