<style>
.ftimg-full-width {
    /* margin: auto; */
    position: relative;
}

.ftimg-full-width .gradient {
    background-image: linear-gradient(to bottom, rgba(245, 246, 252, 0), #022b4b 98%);
    height: 200px;
    width: 100%;
    bottom: 0;
    position: absolute;
}

.ftimg-full-width img {
    /* width:100%; */
    /* width: 1920px; */
    width: 100%;
    /* height: 500px; */
    height: 100%;
    object-fit: cover;

}

h1.article-title {
    position: absolute;
    bottom: 0;
    color: white !important;
    z-index: 1;
    left: 60px;
    margin-bottom: 4rem;
}

h1.no-position {
    position: unset;
    margin-bottom: unset;
    margin-left: 5.2%;
    color: #545454 !important;
    max-width: 1440px;
    width: 100%;
    margin: auto;
}
</style>

<?php
    $_post = $block->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null);
?>
<?php if ($featuredImage = $_post->getFeaturedImage()): ?>
<?php
         $featuredImgAlt = $_post->getData('featured_img_alt');
         if (!$featuredImgAlt) {
             $featuredImgAlt = $_postName;
         }
     ?>
<div class="post-ftimg-hld ftimg-full-width test">
    <img src="<?= $block->escapeUrl($featuredImage) ?>" alt="<?= $block->escapeHtml($featuredImgAlt) ?>" />
    <h1 class="article-title"><?= $block->escapeUrl($_postName) ?></h1>
    <div class="gradient"></div>
</div>
<?php else:?>
<h1 class="article-title no-position"><?= $block->escapeUrl($_postName) ?></h1>
<?php endif; ?>