<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Newsletter $block */
?>
<?= $block->getChildHtml('form_before') ?>
<form class="form form-newsletter-manage" action="<?= $block->escapeUrl($block->getAction()) ?>" method="post" id="form-validate">
    <fieldset class="fieldset">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="legend"><span><?= $block->escapeHtml(__('Subscription option')) ?></span></legend><br>
        <div class="field choice">
            <label class="check-containers">
                <input type="checkbox" name="is_subscribed" id="subscription" value="1" title="<?= $block->escapeHtmlAttr(__('General Subscription')) ?>" <?php if ($block->getIsSubscribed()) : ?> checked="checked" <?php endif; ?> class="checkbox">
                <span class="cus-checks"></span>
            </label>
            <label for="subscription" class="subs-label"><span><?= $block->escapeHtml(__('Subscription')) ?></span></label>

        </div>
        <?php /* Extensions placeholder */ ?>
        <?= $block->getChildHtml('customer.form.newsletter.extra') ?>
    </fieldset>
    <span class="newletter-text">What includes subscription text to be taken to be received, consectetur adipiscing elit, sa aliqua. Ut enim ad minim veniam, quis nostrud exercitation
    </span>
    <div class="actions-toolbar">
        <div class="primary"><button type="submit" title="<?= $block->escapeHtmlAttr(__('Subscribe Now')) ?>" class="action save primary"><span><?= $block->escapeHtml(__('Subscribe Now')) ?></span></button></div>
    </div>
</form>
<?php /* Extensions placeholder */ ?>
<?= $block->getChildHtml('customer.form.newsletter.extra2') ?>