<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// @codingStandardsIgnoreFile

/** @var \Magento\Sales\Block\Order\History $block */
?>
<?php $_orders = $block->getOrders();
$_frog_orders = $block->getCustomerOrders();

print_r($_frog_orders);

//$orders = $_frog_orders['orders'];
if(empty($orders)) {
  echo "You have not placed any orders";
}
else {
foreach ($orders as $order) {
    $invoice = $order['invoice'];
    $order_details = $block->getOrderDetails($invoice);
?>
    <?php echo "order date: " . $order_details['orderinfo']['saledate']; ?><br>
    <?php echo "estimated delivery date: " . $order_details['orderinfo']['etadate']; ?><br>
    <?php echo "delivery date: " . $order_details['orderinfo']['deldate']; ?><br>
    <?php echo "delivery time: " . $order_details['orderinfo']['scheduledtime']; ?><br>
    <?php echo "total: " . $order_details['orderinfo']['total']; ?><br>
    <?php echo "sub total: " . $order_details['orderinfo']['subtotal']; ?><br>
    <?php echo "delivery charge: " . $order_details['orderinfo']['delcharge']; ?><br>
    <?php echo "invoice: " . $order_details['orderinfo']['invoicenumber']; ?><br>
    <?php echo "Payment method: " . $order_details['orderinfo']['howtakendescription']; ?><br>
    <?php echo "address: " . $order_details['cusinfo']['shiptoname'] . " " . $order_details['cusinfo']['shiptoaddress'] . " " . $order_details['cusinfo']['shiptocity'] . " " . $order_details['cusinfo']['shiptostate'] . " " . $order_details['cusinfo']['shiptozip']; ?><br>
    <?php echo "phone number: " . $order_details['cusinfo']['shiptophone']; ?><br>
    <?php
    if (!empty($order_details['orderinfo']['etadate'])) {
    ?>
        <?php echo "Ordered and estimated delivery on: " . $order_details['orderinfo']['etadate'] ?><br>
    <?php
    } else if ($order_details['orderinfo']['deldate'] == date('m/d/Y')) {
    ?>
        <?php echo "Scheduled time: " . $order_details['orderinfo']['scheduledtime']; ?><br>
    <?php
    } else {
    ?>
        <?php echo "Order delivered on: " . $order_details['orderinfo']['deldate']; ?><br>
        <?php
    }
    $order_items = $order_details['items'];
    foreach ($order_items as $item) {
        $serviceSkus = array("MAN-DELIVERY", "MAN-PREMIUM-DELIVERY", "MAN-DISCOUNT", "MAN-RECYCLE-FEE", "MAN-EXPERT/SET-UP");
        if (!in_array($item['skunumber'], $serviceSkus)) {
        ?>

            <?php echo "sku: " . $item['skunumber']; ?><br>
            <?php echo "price: " . $item['price']; ?><br>
            <?php echo "quantity: " . $item['qty']; ?><br>
        <?php
        }
        if ($item['skunumber'] == "MAN-EXPERT/SET-UP") {
        ?>
            <?php echo "Assembly charge: " . $item['price']; ?><br>
<?php
        }
    }
}
}
?>
<?= $block->getChildHtml('info') ?>
<?php if ($_orders && count($_orders)) : ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?= $block->escapeHtml(__('Order #')) ?></th>
                    <th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                    <?= $block->getChildHtml('extra.column.header') ?>
                    <th scope="col" class="col total"><?= $block->escapeHtml(__('Order Total')) ?></th>
                    <th scope="col" class="col status"><?= $block->escapeHtml(__('Status')) ?></th>
                    <th scope="col" class="col actions"><?= $block->escapeHtml(__('Action')) ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_orders as $_order) : ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id"><?= $block->escapeHtml($_order->getRealOrderId()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date"><?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?></td>
                        <?php $extra = $block->getChildBlock('extra.container'); ?>
                        <?php if ($extra) : ?>
                            <?php $extra->setOrder($_order); ?>
                            <?= $extra->getChildHtml() ?>
                        <?php endif; ?>
                        <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total"><?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status"><?= $block->escapeHtml($_order->getStatusLabel()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                            <a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="action view">
                                <span><?= $block->escapeHtml(__('View Order')) ?></span>
                            </a>
                            <?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($_order->getEntityId())) : ?>
                                <a href="#" data-post='<?= /* @noEscape */
                                                        $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                                            ->getPostData($block->getReorderUrl($_order))
                                                        ?>' class="action order">
                                    <span><?= $block->escapeHtml(__('Reorder')) ?></span>
                                </a>
                            <?php endif ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else : ?>
    <div class="message info empty"><span><?= $block->escapeHtml($block->getEmptyOrdersMessage()) ?></span></div>
<?php endif ?>
