<div data-bind="scope: 'synchronyDBuyMessages'">
    <!-- ko if: messages() && messages().length > 0 -->
    <div role="alert" data-bind="foreach: { data: messages(), as: 'message' }" class="messages">
        <div data-bind="attr: {
            class: 'message-' + message.type + ' ' + message.type + ' message',
            'data-ui-id': 'message-' + message.type
        }">
            <div data-bind="html: message.text"></div>
        </div>
    </div>
    <!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "synchronyDBuyMessages": {
                        "component": "Synchrony_DigitalBuy/js/view/messages"
                    }
                }
            }
        }
    }
</script>
