<style>
.ftimg-full-width {
    /* margin: auto; */
    position: relative;
}

.ftimg-full-width .gradient {
    background-image: linear-gradient(to bottom, rgba(245, 246, 252, 0), #022b4b 98%);
    height: 200px;
    width: 100%;
    bottom: 0;
    position: absolute;
}

.ftimg-full-width img {
    /* width:100%; */
    /* width: 1920px; */
    width: 100%;
    /* height: 500px; */
    height: 100%;
    object-fit: cover;

}
</style>

<?php
    $_post = $block->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null);
?>
<?php if ($featuredImage = $_post->getFeaturedImage()): ?>
<?php
         $featuredImgAlt = $_post->getData('featured_img_alt');
         if (!$featuredImgAlt) {
             $featuredImgAlt = $_postName;
         }
     ?>
<div class="post-ftimg-hld ftimg-full-width">
    <img src="<?= $block->escapeUrl($featuredImage) ?>" alt="<?= $block->escapeHtml($featuredImgAlt) ?>" />
    <div class="gradient"></div>
</div>
<?php endif; ?>