<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_MegaMenu
 */
?>
<?php
/** @var \Amasty\MegaMenu\Block\Html\Topmenu $block */
/** @var \Magento\Framework\Escaper $escaper */
?>

<?php if ($block->isHamburgerEnabled()): ?>
    <section class="ammenu-menu-wrapper -hamburger-top <?= /* @noEscape */ $block->getData('is_porto') ? ' -porto' : '' ?> -icons-<?= /* @noEscape */ $block->getIconStatus() ?>"
             data-ammenu-js="desktop-menu"
             data-mage-init='{
                "amastyMegaMenu":{
                    "stickyStatus": <?= $escaper->escapeJs($block->getStickyState()) ?>,
                    "hamburgerStatus": 1,
                    "desktopStatus": 1
                }
             }'>
        <nav class="ammenu-main-container">
            <ul class="ammenu-items">
                <?php foreach ($block->getMainNodes() as $mainNode): ?><?php
                    if (!$block->isNeedDisplay($mainNode->getId(), $mainNode->getStatus(), $block::DESKTOP_VIEW)) {
                        continue;
                    }

                    $url = $mainNode->getUrl() ?: '#';
                    $widthMode = $escaper->escapeHtml($block->getWidth($mainNode));
                    $widthValue = $block->getWidthValue($mainNode);
                    $mainNodeContent = $block->getContent($mainNode);
                    ?>
                    <li class="ammenu-item -main -<?= $escaper->escapeHtml($widthMode) ?>">
                        <a href="<?= $escaper->escapeUrl($url) ?>"
                           target="<?= $escaper->escapeHtmlAttr($block->getTarget($mainNode)) ?>"
                           class="ammenu-link -main<?= ($mainNodeContent) ? ' -parent' : '' ?> <?= /* @noEscape */ $block->getHighLightClass($mainNode) ?>"
                           title="<?= $escaper->escapeHtmlAttr($mainNode->getName()) ?>">
                            <?= $escaper->escapeHtml($mainNode->getName()) ?>

                            <?php if ($label = $mainNode->getLabel()): ?>
                                <span class="ammenu-label"
                                      style="color: <?= $escaper->escapeHtmlAttr($mainNode->getLabelTextColor() ?: '#000') ?> !important;background-color: <?= $escaper->escapeHtmlAttr($mainNode->getLabelBackgroundColor() ?: '#fff') ?> !important;">
                                <?= $escaper->escapeHtml($label) ?>
                            </span>
                            <?php endif; ?>
                        </a>
                        <?php if (/* @noEscape */ $mainNodeContent): ?>
                            <div class="ammenu-submenu-container ammenu-submenu -<?= $escaper->escapeHtmlAttr($widthMode)?>"
                                 data-ammenu-js="menu-submenu"
                                <?= ($widthValue) ? 'style="width: ' . $escaper->escapeHtmlAttr($widthValue) . 'px"': '' ?>>
                            <section class="ammenu-categories-container ammenu-categories">
                                <?= /* @noEscape */  $mainNodeContent ?>
                            </section>
                        </div>
                    <?php endif;?>
                </li>
            <?php endforeach; ?>
        </ul>
    </nav>
</section>
<?php endif; ?>
