<?php
$spinVisibility = $block->getVisibility();
$helper = $this->helper('Webkul\SpinToWin\Helper\Data');
?>
<form>
</form>
<div class="spin-content-visibilityform admin__scope-old">
    <form data-mage-init='{"validation":{}}' class= "spin-form" action="<?php /* @escapeNotVerified */echo $block->getUrl('spintowin/manage/savevisibility') ?>" enctype="multipart/form-data" method="post" id="spinvisibilityformedit">
        <input type="hidden" value="<?= $spinVisibility->getId()?>" name="entity_id" />
        <?php /* @escapeNotVerified */echo $block->getBlockHtml('formkey')?> 
        <fieldset class="fieldset admin__fieldset">
            <legend class="legend">
                <span><?php /* @escapeNotVerified */echo __('Visibility') ?></span>
            </legend>
            <div class="spin-content-visibilityform-container">
                <div class="field admin__field field-attribute_label required _required">
                    <label class="label" for="visibility_wheel">
                        <span><?php /* @escapeNotVerified */echo __('Spin Wheel Visibility')?></span>
                    </label>
                    <div class="control">
                        <select id="visibility_wheel_depended" name="wheel_depended" class="input-text required-entry">
                            <?php
                            $allowWheel = $helper->getAllow();
                            foreach ($allowWheel as $allowWheelKey => $allowWheelValue) { ?>
                                <option <?php if ($allowWheelKey=='0' && !$spinVisibility->getWheel()) {
                                    echo 'selected';
                                        } elseif ($allowWheelKey=='1' && $spinVisibility->getWheel()) { echo 'selected';} ?> value="<?php echo $allowWheelKey ?>"><?php /* @escapeNotVerified */echo __($allowWheelValue)?></option>
                            <?php }
                            ?>
                        </select>
                    </div>
                    <div class="control">
                        <select id="visibility_wheel" name="wheel[]" type="text" class="select required-entry _required select multiselect admin__control-multiselect" style="height:10em" size="10" multiple="multiple">
                            <?php
                            $wheelView = $helper->getPages();
                            foreach ($wheelView as $wheelViewKey => $wheelViewValue) { ?>
                                <option <?php echo in_array($wheelViewKey, explode(',', $spinVisibility->getWheel())) ? 'selected':''; ?> value="<?php echo $wheelViewKey ?>"><?php /* @escapeNotVerified */echo __($wheelViewValue)?></option>
                            <?php }
                            ?>
                        </select>
                    </div>
                </div>
                <div class="field admin__field field-attribute_label required _required">
                    <label class="label" for="visibility_button">
                        <span><?php /* @escapeNotVerified */echo __('Spin to Win Button Visibility')?></span>
                    </label>
                    <div class="control">
                        <select id="visibility_button_depended" name="button_depended" class="input-text required-entry">
                            <?php
                            $allowButton = $helper->getAllow();
                            foreach ($allowButton as $allowButtonKey => $allowButtonValue) { ?>
                                <option <?php if ($allowButtonKey=='0' && !$spinVisibility->getButton()) {
                                    echo 'selected';
                                        } elseif ($allowButtonKey=='1' && $spinVisibility->getButton()) { echo 'selected';} ?> value="<?php echo $allowButtonKey ?>"><?php /* @escapeNotVerified */echo __($allowButtonValue)?></option>
                            <?php }
                            ?>
                        </select>
                        <div class="note admin__field-note" id="button_depended-note">Applicable only if Show Spin to Win Button is set to "Yes".</div>
                        <div class="control">
                            <select id="visibility_button" name="button[]" type="text" class="input-text required-entry _required select multiselect admin__control-multiselect" style="height:10em" size="10" multiple="multiple">
                                <?php
                                $buttonView = $helper->getPages();
                                foreach ($buttonView as $buttonViewKey => $buttonViewValue) { ?>
                                    <option <?php echo in_array($buttonViewKey, explode(',', $spinVisibility->getButton())) ? 'selected':''; ?> value="<?php echo $buttonViewKey ?>"><?php /* @escapeNotVerified */echo __($buttonViewValue)?></option>
                                <?php }
                                ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="field admin__field field-attribute_label">
                    <label class="label" for="visibility_events">
                        <span><?php /* @escapeNotVerified */echo __('Show Spin Wheel on event')?></span>
                    </label>
                    <div class="control">
                        <select id="visibility_events" name="events[0]" type="text" class="input-text">
                        <option <?php echo ""==$spinVisibility->getEvents()? 'selected':''; ?> value=""><?php /* @escapeNotVerified */echo __("Please select")?></option>
                            <?php
                            $visibilityEvents = $helper->getEvents();
                            foreach ($visibilityEvents as $visibilityEventsKey => $visibilityEventsValue) { ?>
                                <option <?php echo $visibilityEventsKey==explode('_', $spinVisibility->getEvents())[0]? 'selected':''; ?> value="<?php echo $visibilityEventsKey ?>"><?php /* @escapeNotVerified */echo __($visibilityEventsValue)?></option>
                            <?php }
                            ?>
                        </select>
                    </div>
                    <div class="control">
                        <input id="visibility_events_depended" name="events[1]" type="text" class="input-text required-entry validate-greater-than-zero" value="<?php echo isset(explode('_', $spinVisibility->getEvents())[1]) ? explode('_', $spinVisibility->getEvents())[1]:'' ?>" aria-required="true" autocomplete="off">
                    </div>
                </div>
                <button title="<?php /* @escapeNotVerified */echo __('Update Visibility') ?>" type="button" id="update-spinvisibilityform" class="action-default save spin-save spin-save-ajax" data-spin-bind-form="spinvisibilityformedit">
                    <span><?php /* @escapeNotVerified */echo __('Update Visibility') ?></span>
                    <span class="admin__page-nav-item-messages">
                        <span class="admin__page-nav-item-message _changed">
                            <span class="admin__page-nav-item-message-icon"></span>
                            <span class="admin__page-nav-item-message-tooltip" data-bind="i18n: 'Changes have been made to this section that have not been saved.'"></span>
                        </span>
                    </span>
                </button>
            </div>
        </fieldset>
    </form>
</div>
<?php
$spinButton = $block->getButton();
?>
<div class="spin-content-buttonform admin__scope-old">
    <fieldset class="fieldset admin__fieldset">
        <legend class="legend">
            <span><?php /* @escapeNotVerified */echo __('Spin to Win Button') ?></span>
        </legend>
        <div class="spin-content-buttonform-container">
            <div class="spin-content-buttonform-edit">
                <form data-mage-init='{"validation":{}}' class= "spin-form" action="<?php /* @escapeNotVerified */echo $block->getUrl('spintowin/manage/savebutton') ?>" enctype="multipart/form-data" method="post" id="spinbuttonformedit">
                    <input type="hidden" value="<?= $spinButton->getId()?>" name="entity_id" />
                    <?php /* @escapeNotVerified */echo $block->getBlockHtml('formkey')?>    
                    <fieldset class="fieldset admin__fieldset">
                        <legend class="legend">
                            <span><?php /* @escapeNotVerified */echo __('Configure Button') ?></span>
                        </legend>
                        <div class="field admin__field field-attribute_label required _required">
                            <label class="label" for="buttonform_show">
                                <span><?php /* @escapeNotVerified */echo __('Show Spin to Win Button')?></span>
                            </label>
                            <div class="control">
                                <select id="buttonform_show" name="show" type="text" class="input-text required-entry">
                                    <option <?php echo $spinButton->getShow()? 'selected':''; ?> value="1"><?php /* @escapeNotVerified */echo __('Yes')?></option>
                                    <option <?php echo $spinButton->getId() && !$spinButton->getShow()? 'selected':''; ?> value="0"><?php /* @escapeNotVerified */echo __('No')?></option>                        
                                </select>
                            </div>
                        </div>
                        <div class="field admin__field  field-attribute_label  required _required">
                            <label class="label" for="buttonform_label">
                                <span><?php /* @escapeNotVerified */echo __('Button Label')?></span>
                            </label>
                            <div class="control">
                                <input type="text" id="buttonform_label" name="label" value="<?php echo $spinButton->getLabel()?>" class="input-text spin-bind-text required-entry validate-no-html-tags" data-spin-bind="spin-buttonform-button-text-preview" />
                            </div>
                        </div>
                        <div class="field admin__field  field-attribute_label  required _required">
                            <label class="label" for="buttonform_background_color">
                                <span><?php /* @escapeNotVerified */echo __('Background Color')?></span>
                            </label>
                            <div class="control">
                                <span class="color-pick spin-color-box" data-role="color-pick" data-mage-init='{"colorPickerFunction":{"spanBackgroundColor" : "<?php echo $spinButton->getBackgroundColor()?>", "getActiveColorPickerStatus" : "1", "backgroundWidthSelector" : "#buttonform_background_color"}}'></span>
                                <input type="text" id="buttonform_background_color" name="background_color" value="<?php echo $spinButton->getBackgroundColor()?>" class="input-text spin-color-input spin-bind-style required-entry" data-spin-bind="spin-buttonform-button-preview" data-spin-bind-prop='background-color' />
                            </div>
                        </div>
                        <div class="field admin__field  field-attribute_label  required _required">
                            <label class="label" for="buttonform_text_color">
                                <span><?php /* @escapeNotVerified */echo __('Text Color')?></span>
                            </label>
                            <div class="control">
                                <span class="color-pick spin-color-box" data-role="color-pick" data-mage-init='{"colorPickerFunction":{"spanBackgroundColor" : "<?php echo $spinButton->getTextColor()?>", "getActiveColorPickerStatus" : "1", "backgroundWidthSelector" : "#buttonform_text_color"}}'></span>
                                <input type="text" id="buttonform_text_color" name="text_color" value="<?php echo $spinButton->getTextColor()?>" class="input-text spin-color-input spin-bind-style required-entry" data-spin-bind="spin-buttonform-button-preview" data-spin-bind-prop='color' />
                            </div>
                        </div>
                        <div class="field admin__field  field-attribute_label required _required">
                            <label class="label" for="buttonform_image">
                                <span><?php /* @escapeNotVerified */echo __('Spin to Win image')?></span>
                            </label>
                            <div class="control">
                                <input type="file" id="buttonform_image" name="image" value="" class="input-text spin-files" data-spin-bind-image="buttonform_image_preview"  data-upload-id="buttonform_image_hidden" data-upload-url="<?= $block->getUploadUrl(); ?>" />
                                <input type="hidden" id="buttonform_image_hidden" name="image" value="<?php echo $spinButton->getImage()?>" class="required-entry"/>
                                <div class="spin-image-preview-container">
                                    <img src="<?php echo ($spinButton->getImage() ? $block->getMediaUrl($spinButton->getImage()):'') ?>" class="spin-image spin-image-preview">
                                    <span class="spin-image-delete" data-delete="buttonform_image"></span>
                                </div>
                                <div class="spin-buttonform-button-images">
                                <?php
                                $spintowinButtonImage = $helper->getSpintowinButtonImage();
                                foreach ($spintowinButtonImage as $spintowinButtonImageKey => $spintowinButtonImageValue) { ?>
                                    <img src="<?php echo $block->getMediaUrl($spintowinButtonImageValue) ?>" class="spin-image spin-buttonform-button-image" data-spin-src="<?php echo $spintowinButtonImageValue?>"/>
                                <?php }?>
                                </div>
                                <button type="button" class="spin-button spin-upload-button spin-files-button" data-triggerid="buttonform_image">Browse Files...</button>
                                <div class="note admin__field-note" id="buttonform_image-note">Please use 54px X 54px images.</div>                
                            </div>
                        </div>
                        <button title="<?php /* @escapeNotVerified */echo __('Update Button') ?>" type="button" id="update-spinbuttonform" class="action-default save spin-save spin-save-ajax" data-spin-bind-form="spinbuttonformedit">
                            <span><?php /* @escapeNotVerified */echo __('Update Button') ?></span>
                            <span class="admin__page-nav-item-messages">
                                <span class="admin__page-nav-item-message _changed">
                                    <span class="admin__page-nav-item-message-icon"></span>
                                    <span class="admin__page-nav-item-message-tooltip" data-bind="i18n: 'Changes have been made to this section that have not been saved.'"></span>
                                </span>
                            </span>
                        </button>
                    </fieldset>
                </form>
            </div>
            <div class="spin-content-buttonform-preview">
                <fieldset class="fieldset admin__fieldset">
                    <legend class="legend">
                        <span><?php /* @escapeNotVerified */echo __('Preview Button') ?></span>
                    </legend>
                </fieldset>
                <div class='spin-content-buttonform-preview-data'>
                    <div style="width: 100%;position:relative;height: 100%;">
                        <button type="button" class="action-default spin-buttonform-button-preview"><img class="spin-buttonform-image-preview buttonform_image_preview" src="<?php echo ($spinButton->getImage() ? $block->getMediaUrl($spinButton->getImage()):'') ?>" /><span class="spin-buttonform-button-text-preview"></span></button>
                    </div>
                </div>
            </div>
        </div>
    </fieldset>
</div>


<?php
$spinCoupon = $block->getCoupon();
?>
<div class="spin-content-couponform admin__scope-old">
    <fieldset class="fieldset admin__fieldset">
        <legend class="legend">
            <span><?php /* @escapeNotVerified */echo __('Won Coupon Button') ?></span>
        </legend>
        <div class="spin-content-couponform-container">
            <div class="spin-content-couponform-edit">
                <form data-mage-init='{"validation":{}}' class= "spin-form" action="<?php /* @escapeNotVerified */echo $block->getUrl('spintowin/manage/savecoupon') ?>" enctype="multipart/form-data" method="post" id="spincouponformedit">
                    <input type="hidden" value="<?= $spinCoupon->getId()?>" name="entity_id" />
                    <?php /* @escapeNotVerified */echo $block->getBlockHtml('formkey')?>    
                    <fieldset class="fieldset admin__fieldset">
                        <legend class="legend">
                            <span><?php /* @escapeNotVerified */echo __('Configure Button') ?></span>
                        </legend>
                        <div class="field admin__field field-attribute_label required _required">
                            <label class="label" for="couponform_show">
                                <span><?php /* @escapeNotVerified */echo __('Show Won Coupon Button')?></span>
                            </label>
                            <div class="control">
                                <select id="couponform_show" name="show" type="text" class="input-text required-entry">
                                    <option <?php echo $spinCoupon->getShow()? 'selected':''; ?> value="1"><?php /* @escapeNotVerified */echo __('Yes')?></option>
                                    <option <?php echo $spinCoupon->getId() && !$spinCoupon->getShow()? 'selected':''; ?> value="0"><?php /* @escapeNotVerified */echo __('No')?></option>                        
                                </select>
                            </div>
                        </div>
                        <div class="field admin__field  field-attribute_label  required _required">
                            <label class="label" for="couponform_label">
                                <span><?php /* @escapeNotVerified */echo __('Button Label')?></span>
                            </label>
                            <div class="control">
                                <input type="text" id="couponform_label" name="label" value="<?php echo $spinCoupon->getLabel()?>" class="input-text spin-bind-text required-entry validate-no-html-tags" data-spin-bind="spin-couponform-button-text-preview" />
                            </div>
                        </div>
                        <div class="field admin__field  field-attribute_label  required _required">
                            <label class="label" for="couponform_background_color">
                                <span><?php /* @escapeNotVerified */echo __('Background Color')?></span>
                            </label>
                            <div class="control">
                                <span class="color-pick spin-color-box" data-role="color-pick" data-mage-init='{"colorPickerFunction":{"spanBackgroundColor" : "<?php echo $spinCoupon->getBackgroundColor()?>", "getActiveColorPickerStatus" : "1", "backgroundWidthSelector" : "#couponform_background_color"}}'></span>
                                <input type="text" id="couponform_background_color" name="background_color" value="<?php echo $spinCoupon->getBackgroundColor()?>" class="input-text spin-color-input spin-bind-style required-entry" data-spin-bind="spin-couponform-button-preview" data-spin-bind-prop='background-color' />
                            </div>
                        </div>
                        <div class="field admin__field  field-attribute_label  required _required">
                            <label class="label" for="couponform_text_color">
                                <span><?php /* @escapeNotVerified */echo __('Text Color')?></span>
                            </label>
                            <div class="control">
                                <span class="color-pick spin-color-box" data-role="color-pick" data-mage-init='{"colorPickerFunction":{"spanBackgroundColor" : "<?php echo $spinCoupon->getTextColor()?>", "getActiveColorPickerStatus" : "1", "backgroundWidthSelector" : "#couponform_text_color"}}'></span>
                                <input type="text" id="couponform_text_color" name="text_color" value="<?php echo $spinCoupon->getTextColor()?>" class="input-text spin-color-input spin-bind-style required-entry" data-spin-bind="spin-couponform-button-preview" data-spin-bind-prop='color' />
                            </div>
                        </div>
                        <button title="<?php /* @escapeNotVerified */echo __('Update Won Coupon') ?>" type="button" id="update-spincouponform" class="action-default save spin-save spin-save-ajax" data-spin-bind-form="spincouponformedit">
                            <span><?php /* @escapeNotVerified */echo __('Update Won Coupon') ?></span>
                            <span class="admin__page-nav-item-messages">
                                <span class="admin__page-nav-item-message _changed">
                                    <span class="admin__page-nav-item-message-icon"></span>
                                    <span class="admin__page-nav-item-message-tooltip" data-bind="i18n: 'Changes have been made to this section that have not been saved.'"></span>
                                </span>
                            </span>
                        </button>
                    </fieldset>
                </form>
            </div>
            <div class="spin-content-couponform-preview">
                <fieldset class="fieldset admin__fieldset">
                    <legend class="legend">
                        <span><?php /* @escapeNotVerified */echo __('Preview Button') ?></span>
                    </legend>
                </fieldset>
                <div class='spin-content-couponform-preview-data'>
                    <div style="width: 100%;position:relative;height: 100%;">
                        <button type="button" class="action-default spin-couponform-button-preview">
                            <img class="spin-couponform-icon" src="<?php echo $block->getMediaUrl('spintowin/image/coupon.png') ?>" />
                            <span class="spin-couponform-button-text-preview"></span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </fieldset>
</div>


<script type="text/x-magento-init">
    {
        "*": {
            "trigger": {}
        }
    }
</script>
