<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
?>


<div class="myaccount-page">
    <div class="row ">
        <div class="col-12 col-lg-6 myorders">
            <div class="my-account-orders">
                <div class="order">
                    <div class="title">
                        <p>My Orders</p>
                    </div>
                    <div class="content">
                        <p class="reward-text">Track, Order Details, or buy things again</p>
                        <a href="<?= $block->escapeUrl($block->getUrl('sales/order/history')) ?>" class="btn btn-primary">View all Oders</a>
                    </div>
                </div>
            </div>
        </div>
        <div class=" col-12 col-lg-6 myrewards">
            <div class="order">
                <div class="title">
                    <p>Reward Points : 1625</p>
                </div>
                <div class="content">
                    <div class="contents">
                        <img class="reward-image" src='<?php echo $this->getViewFileUrl('images/info.png') ?>' alt="">
                        <p>1000 Points = 10% Discount</p>
                    </div>
                    <div class="contentss">
                        <a href="#" class="btn btn-primary">View Rewards</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-12 col-lg-6 left-division">
        <div class="mywishlist"><?php
                                // echo $this->getLayout()->createBlock("Magento\Wishlist\Block\Customer\Wishlist")->setTemplate("Magento_Wishlist::view.phtml")->toHtml();
                                ?></div>
        <div class="newsletter-account"><?php if ($block->isNewsletterEnabled()) : ?>
                <div class="box box-newsletter">
                    <strong class="box-title">
                        <span><?= $block->escapeHtml(__('Newsletters')) ?></span>
                    </strong>
                    <div class="box-content">
                        <p>
                            <?php if ($block->getIsSubscribed()) : ?>
                                <?= $block->escapeHtml(__('You are subscribed to "General Subscription".')) ?>
                            <?php else : ?>
                                <?= $block->escapeHtml(__('You aren\'t subscribed to our newsletter.')) ?>
                                <?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_Customer::form/newsletter.phtml")->toHtml(); ?>

                            <?php endif; ?>
                        </p>
                    </div>

                </div>
            <?php endif; ?>
        </div>

    </div>
    <div class="col-12 col-lg-6 right-division">
        <div class="informations">
            <div class="block block-dashboard-info">
                <!-- <div class="block-title"><strong><? //$block->escapeHtml(__('Account Information')) 
                                                        ?></strong></div> -->
                <div class="box box-information">
                    <strong class="box-title">
                        <h3><?= $block->escapeHtml(__('Personal Information')) ?></h3>
                    </strong>
                    <div class="box-content row">
                        <div class="col-md-6 box-one">
                            <div class="mobile">
                                <p class="heading">Name:</p>
                                <p class="content"><?= $block->escapeHtml($block->getName()) ?></p>
                            </div>
                            <div class="mobile">
                                <p class="heading">Mobile:</p>
                                <p class="content"><?php echo "primary - " ?><?= $block->escapeHtml($block->getCustomer()->getCustomAttribute('mobile')->getValue()) ?></p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="email">
                                <p class="heading">Email: </p>
                                <p class="content"><?= $block->escapeHtml($block->getCustomer()->getEmail()) ?></p>
                            </div>
                            <div class="pswd">
                                <p class="heading">Password</p>
                                <p class="content">*********</p>
                            </div>

                        </div>
                        <?= $block->getChildHtml('customer.account.dashboard.info.extra'); ?>
                    </div>
                    <div class="box-actions edit_info_btn">
                        <a class="action edit btn btn-primary" href="<?= $block->escapeUrl($block->getUrl('customer/account/edit')) ?>">
                            <span><?= $block->escapeHtml(__('Edit Info')) ?></span>
                        </a>
                    </div>
                </div>

                <?= $block->getChildHtml('additional_blocks'); ?>
            </div>
        </div>

        <div class="shipping-address"><?php //echo $this->getLayout()->createBlock("Magento\Customer\Block\Account\Dashboard\Address")->setTemplate("Magento_Customer::account/dashboard/address.phtml")->toHtml(); 
                                        ?></div>

    </div>
</div>